word_list =  ['absence', 'act', 'activity', 'actor', 'application', 'army', 'assistant', 'atmosphere', 'bag', 'beer', 'bet', 'bone', 'bottle', 'boy', 
              'breath', 'budget', 'building', 'captain', 'care', 'castle', 'ceiling', 'chance', 'choice', 'cigarette', 'circumstance', 'commission', 
              'conduct', 'conference', 'connection', 'conscience', 'construction', 'construction', 'contact', 'control', 'credit', 'cross', 'dance', 
              'daughter', 'definition', 'delight', 'department', 'development', 'distance', 'dog', 'dream', 'editor', 'elections', 'element', 'ending', 
              'entrance', 'evil', 'experiment', 'explosion', 'feature', 'festival', 'fight', 'food', 'friendship', 'frontier', 'function', 'fund', 
              'future', 'gate', 'glasses', 'glory', 'gold', 'goodness', 'goods', 'guilt', 'hostess', 'household', 'impression', 'indicator', 'influence',
              'initiative', 'king', 'kitchen', 'lake', 'leaf', 'library', 'limit', 'lord', 'machine', 'magnitude', 'major', 'man', 'management', 
              'marriage',  'mass', 'metal', 'meter', 'milk', 'moment', 'monastery', 'mountain', 'multitude', 'necessity', 'note', 'officer', 'order', 
              'pain', 'paint', 'palace', 'parameter', 'particularity', 'peace', 'pen', 'personality', 'pistol', 'pleasure', 'plot', 'pocket', 'poetry', 
              'practice', 'preparation', 'prize', 'production', 'profession', 'prosecutor', 'provision', 'reader', 'reading', 'reform', 'refusal', 
              'republic', 'responsibility', 'rest', 'result', 'ring', 'risk', 'river', 'sand', 'scale', 'scientist', 'seal', 'settlement', 'ship', 
              'signal', 'sister', 'smoke', 'snow', 'sofa', 'soil', 'sound', 'source', 'sphere', 'sport', 'star', 'status', 'stone', 'story', 'subdivision', 
              'sum', 'surname', 'surprise', 'table', 'tail', 'teacher', 'tear', 'technique', 'technology', 'tendency', 'theory', 'thing', 'tooth', 
              'transport', 'turn', 'upbringing', 'version', 'victory', 'village', 'village', 'weight', 'will', 'witness', 'worker', 'zombie', 'zone', 'zoo', 
             ]

